vegova = [
    ("Glava pred roko", "Tomo Omahna"),
    ("S katere hoste pa si ti pršu?", "Tomo Omahna"),
    ("Dej odpri okn! Zard zvoka!", "Tomo Omahna"),
    ("Za kok si kupil suknjič? Po dobavni ceni.", "Tomo Omahna"),
    ("Ubi se", "Tomo Omahna"),
    ("Za vsako rit palca raste", "Tomo Omahna"),
    ("Ena bl resna plučnca me je zagrabla, pa so me napumpal", "Tomo Omahna"),
    ("Kvas lesen", "Tomo Omahna"),
    ("Naročil sem vam da mi prepleskate fasado, vi mi pa rože zalivate, in pričakujete plačilo", "Tomo Omahna"),
    ("Jao", "Tomo Omahna"),
    ("Fantje, nismo kupil BMW-ja da bomo na bencinu šparal", "Tomo Omahna"),
    ("Če pogledaš ekipo camerona so vsi črni pa če pogledate na tribuno so tud vsi črni pa če pogledaš trenerja je tud on črn. Zakaj je tako? Ker so pojedl vse bele.", "Tomo Omahna"),
    ("Rusov je 140 miljonov, američanov pa 300 miljonov. Zakaj je tko? Ker američani štejejo črnce kt ljudi", "Tomo Omahna"),
    ("Zanimivo", "Lidija Gorišek"),
    ("A ste slišali za tiste viruse ki nič ne delajo? To so uni albanski virusi", "Dušan Sitar"),
    ("Orehova torta ... njam", "Janja Žlebnik"),
    ("Ecka pecka pošto pelja, pošta se zvrne, ecka pecka prdne", "Marko Kastelic"),
    ("Naši južni bratje", "Marko Kastelic"),
    ("Pardon, samo da majnika ubijem", "Marko Kastelic"),
    ("Tiho fantje", "Matjaž Majnik"),
    ("Športna smola", "Marko Kastelic"),
    ("Eeeh kako se že temu reče", "Marko Kastelic"),
    ("Rečmo da hočeš petko pa prideš do mene s sekirco pa mi rečeš, da hočeš petko. Jaz te uprašam, zakaj bi ti to petko dal, nato pa ti pokažeš sekirco. A bi ti poj dal petko? Ne, js bi še večjo sekirco potegnu!", "Marko Kastelic"),
    ("Šlebič tebe je itak težko ne opazit", "Matjaž Majnik"),
    ("BENJAMIN", "Katja Lasbaher"),
    ("Gospod, če imate težave z želodcem, prosim če lahko trpite v tišini", "Karin Kastelic"),
    ("V osnovni šoli smo delali IQ test, imela sm VČASIH okol 120, ampak ko ženska rodi otroka baje da odmre 20% možganskih celic. Jaz imam 3 otroke.", "Karin Kastelic"),
    ("Ja a je to dobr? Ja verjetn je dobr", "Miki"),
    ("Fantje zdej pa se umirite da premislimo, kaj bomo dali v GROUP BY stavek", "Matjaž Majnik"),
    ("...pridemo do Grosuplja, to je tm k so se turki mal predolg ustavl", "Marko Kastelic"),
    ("*papagaj noises* I'm a parrot!", "Mojca Fink"),
]

fri = [
    ("Situacija ni rožnata", "Gašper Fijavž"),
    ("To metodo so uporabljali že v Vojvodini", "Aleksandar Jurišić"),
    ("Moj pes je tok pametn, da je zjutri vedu da bova zamudla, zato sva šla z avtom", "Aleksandar Jurišić"),
    ("DADI MIR", "Aleksandar Jurišić"),
    ("Moja žena je tok nesrečna", "Janez Demšar"),
    ("Dejte tole med odmorom prebavit", "Gašper Fijavž"),
    ("Če se nekaj obnaša kot raca, gaga kot raca, potem res je raca", "Gašer Fijavž"),
    ("Zakaj je treba znt štet", "Gašper Fijavž"),
    ("B kar nekako izgine", "Gašer Fijavž"),
    ("Prehiter flomaster je", "Gašper Fijavž"),
    ("Ta tavtologija je klobasa", "Gašper Fijavž"),
    ("Spodaj podpisani Bubble Sort, vpisna številka 923456781, prosim za odobritev statusa algoritma s posebnimi potrebami", "Janez Demšar"),
    ("Da o moških, ki v pajkicah tekajo okrog fakultete (ravno danes se je s FRI -- sredi belega dne! vpričo mimoidočih študentov! -- spet priklatil en tak nespodobnež in dva somišljenika) ne izgubljamo prepotrebnih grdih besed.", "Janez Demšar"),
    ("Na tole sem napisal in pobrisal že štiri odgovore. Prvi je bil v caps locku. Drugi je bil sarkastičen. Tretji brezzvezen. Četrti predolg. Vse, kar sem naredil za zdaj, je, da sem kolega Nejca suspendiral iz Učilnice. Ali le iz tega predmeta ali iz vseh, ne vem. Glede na to, da je ne zna uporabljati, upam, da iz vseh, saj sem s tem morda naredil uslugo še kakemu drugemu profesorju.", "Janez Demšar"),
    ("Kje je miš", "Peter Peer"),
    ("Klele imamo kr velke kumare v glavnem", "Aleksandar Jurišić"),
    ("Dadi sedi, dej tačko, rollover", "Aleksandar Jurišić"),
    ("Porazdelitev KiKi bombona", "Aleksandar Jurišić"),
    ("KiKi bombon ni sam za pojest, treba ga je ogret v žepu in ga oblikovat potem v kocko, vzet flumaster pa označit vsako stran od 1-6", "Aleksandar Jurišić"),
    ("En se pokrajša, en pač ne, tak pač je, takšno je življenje", "Aleksandar Jurišić"),
    ("Zdej pr plačah k ni komunizem/kapitalizem, se je treba pogajat, en dobi več, eden manj, ni fer, ampak večinoma gre po zaslugah", "Aleksandar Jurišić"),
    ("V KOČO!", "Aleksandar Jurišić"),
    ("Je nič ampak ni nič", "Aleksandar Jurišić"),
    ("Hčerka od enga prijatla, je en dan lizala sladoled, pa ni gledla pa ji je sladoled padu na tla, pa je rekla da ji je padu na tla, pa reče fotr, ja js sm ga že plaču, kaj naj ti zdej js, pa reče hčerka 'not fair, not fair, not fair'. Življenje ni fer, ni fer, ni fer... ", "Aleksandar Jurišić"),
    ("Prejšnji teden ne, ker smo se filal z jajčki", "Peter Peer"),
    ("Bejži v vrsto!", "Peter Peer"),
]